//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend
{
    public partial class AccessDenied
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTitle;

        /// <summary>
        /// lblDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDescription;

        /// <summary>
        /// lnkLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkLogin;

        /// <summary>
        /// lnkPortal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkPortal;

        /// <summary>
        /// spnTimestamp control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spnTimestamp;
    }
}
