using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace _241611JalopEventsManagement.Backend.Repository
{
    /// <summary>
    /// Database connection provider and query helper for UniversityEventDB.
    /// Connects to the database generated by 01_DatabaseSchema.sql.
    /// </summary>
    public static class DatabaseConnection
    {
        private const string ConnectionStringName = "UniversityEventDBConnection";
        private const string FallbackConnectionName = "DefaultConnection";

        /// <summary>
        /// Retrieves the connection string configured in Web.config.
        /// </summary>
        public static string ConnectionString
        {
            get
            {
                var connSetting = ConfigurationManager.ConnectionStrings[ConnectionStringName]
                                  ?? ConfigurationManager.ConnectionStrings[FallbackConnectionName];

                if (connSetting == null || string.IsNullOrWhiteSpace(connSetting.ConnectionString))
                {
                    // Default local fallback pointing to UniversityEventDB
                    return @"Data Source=localhost;Initial Catalog=UniversityEventDB;Integrated Security=True;TrustServerCertificate=True;";
                }

                return connSetting.ConnectionString;
            }
        }

        /// <summary>
        /// Creates a new, closed SqlConnection instance.
        /// Wrap in a using statement when utilizing.
        /// </summary>
        public static SqlConnection GetConnection()
        {
            return new SqlConnection(ConnectionString);
        }

        /// <summary>
        /// Creates and opens a new SqlConnection instance.
        /// Wrap in a using statement when utilizing.
        /// </summary>
        public static SqlConnection GetOpenConnection()
        {
            var connection = GetConnection();
            if (connection.State != ConnectionState.Open)
            {
                connection.Open();
            }
            return connection;
        }

        /// <summary>
        /// Tests connectivity to UniversityEventDB with a lightweight query (SELECT 1).
        /// </summary>
        /// <param name="errorMessage">Contains the error message if the connection fails; otherwise null.</param>
        /// <returns>True if connection succeeds; false otherwise.</returns>
        public static bool TestConnection(out string errorMessage)
        {
            errorMessage = null;
            try
            {
                using (var conn = GetOpenConnection())
                using (var cmd = new SqlCommand("SELECT 1;", conn))
                {
                    cmd.CommandTimeout = 5;
                    cmd.ExecuteScalar();
                }
                return true;
            }
            catch (Exception ex)
            {
                errorMessage = ex.Message;
                return false;
            }
        }

        #region Helper ADO.NET Methods for Repositories

        /// <summary>
        /// Executes an INSERT, UPDATE, or DELETE query with parameters.
        /// </summary>
        public static int ExecuteNonQuery(string query, params SqlParameter[] parameters)
        {
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(query, conn))
            {
                if (parameters != null && parameters.Length > 0)
                {
                    cmd.Parameters.AddRange(parameters);
                }
                return cmd.ExecuteNonQuery();
            }
        }

        /// <summary>
        /// Executes a scalar query (e.g., SELECT COUNT, SCOPE_IDENTITY) and returns the first column of the first row.
        /// </summary>
        public static object ExecuteScalar(string query, params SqlParameter[] parameters)
        {
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(query, conn))
            {
                if (parameters != null && parameters.Length > 0)
                {
                    cmd.Parameters.AddRange(parameters);
                }
                return cmd.ExecuteScalar();
            }
        }

        /// <summary>
        /// Executes a SELECT query with parameters and fills the result into a DataTable.
        /// </summary>
        public static DataTable ExecuteDataTable(string query, params SqlParameter[] parameters)
        {
            var dataTable = new DataTable();
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(query, conn))
            {
                if (parameters != null && parameters.Length > 0)
                {
                    cmd.Parameters.AddRange(parameters);
                }

                using (var adapter = new SqlDataAdapter(cmd))
                {
                    adapter.Fill(dataTable);
                }
            }
            return dataTable;
        }

        #endregion
    }
}
