using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace _241611JalopEventsManagement.Backend.Repository
{
    /// <summary>
    /// Database connection provider and query helper for UniversityEventDB.
    /// Connects to the database generated by 01_DatabaseSchema.sql.
    /// </summary>
    public static class DatabaseConnection
    {
        private const string ConnectionStringName = "UniversityEventDBConnection";
        private const string FallbackConnectionName = "DefaultConnection";

        /// <summary>
        /// Retrieves the connection string configured in Web.config.
        /// </summary>
        public static string ConnectionString
        {
            get
            {
                var connSetting = ConfigurationManager.ConnectionStrings[ConnectionStringName]
                                  ?? ConfigurationManager.ConnectionStrings[FallbackConnectionName];

                if (connSetting == null || string.IsNullOrWhiteSpace(connSetting.ConnectionString))
                {
                    // Default local fallback pointing to UniversityEventDB
                    return @"Data Source=localhost;Initial Catalog=UniversityEventDB;Integrated Security=True;Encrypt=False;TrustServerCertificate=True;Connect Timeout=3;Pooling=True;";
                }

                return connSetting.ConnectionString;
            }
        }

        #region Circuit Breaker for High Performance Fast-Fail

        private static DateTime _lastConnectionFailureUtc = DateTime.MinValue;
        private const int CircuitBreakerSeconds = 15;

        /// <summary>
        /// Indicates if the connection circuit breaker is tripped due to a recent connection timeout/failure.
        /// When true, subsequent queries fail fast (in 0ms) rather than repeatedly hanging threads.
        /// </summary>
        public static bool IsCircuitBreakerOpen
        {
            get
            {
                if (_lastConnectionFailureUtc == DateTime.MinValue)
                {
                    return false;
                }
                return (DateTime.UtcNow - _lastConnectionFailureUtc).TotalSeconds < CircuitBreakerSeconds;
            }
        }

        public static void RecordConnectionSuccess()
        {
            _lastConnectionFailureUtc = DateTime.MinValue;
        }

        public static void RecordConnectionFailure()
        {
            _lastConnectionFailureUtc = DateTime.UtcNow;
        }

        #endregion

        /// <summary>
        /// Creates a new, closed SqlConnection instance.
        /// Wrap in a using statement when utilizing.
        /// </summary>
        public static SqlConnection GetConnection()
        {
            return new SqlConnection(ConnectionString);
        }

        /// <summary>
        /// Creates and opens a new SqlConnection instance.
        /// Fails fast if the database circuit breaker is open to prevent freezing UI threads.
        /// Wrap in a using statement when utilizing.
        /// </summary>
        public static SqlConnection GetOpenConnection()
        {
            if (IsCircuitBreakerOpen)
            {
                throw new InvalidOperationException("Database connection circuit breaker is open due to recent unreachable database server. Fast-failing to preserve UI responsiveness.");
            }

            try
            {
                var connection = GetConnection();
                if (connection.State != ConnectionState.Open)
                {
                    connection.Open();
                }
                RecordConnectionSuccess();
                return connection;
            }
            catch (Exception)
            {
                RecordConnectionFailure();
                throw;
            }
        }

        /// <summary>
        /// Tests connectivity to UniversityEventDB with a lightweight query (SELECT 1).
        /// Bypasses the circuit breaker to permit active health checking.
        /// </summary>
        /// <param name="errorMessage">Contains the error message if the connection fails; otherwise null.</param>
        /// <returns>True if connection succeeds; false otherwise.</returns>
        public static bool TestConnection(out string errorMessage)
        {
            errorMessage = null;
            try
            {
                using (var conn = GetConnection())
                {
                    conn.Open();
                    using (var cmd = new SqlCommand("SELECT 1;", conn))
                    {
                        cmd.CommandTimeout = 3;
                        cmd.ExecuteScalar();
                    }
                }
                RecordConnectionSuccess();
                return true;
            }
            catch (Exception ex)
            {
                RecordConnectionFailure();
                errorMessage = ex.Message;
                return false;
            }
        }

        #region Helper ADO.NET Methods for Repositories

        /// <summary>
        /// Executes an INSERT, UPDATE, or DELETE query with parameters.
        /// </summary>
        public static int ExecuteNonQuery(string query, params SqlParameter[] parameters)
        {
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(query, conn))
            {
                if (parameters != null && parameters.Length > 0)
                {
                    cmd.Parameters.AddRange(parameters);
                }
                return cmd.ExecuteNonQuery();
            }
        }

        /// <summary>
        /// Executes a scalar query (e.g., SELECT COUNT, SCOPE_IDENTITY) and returns the first column of the first row.
        /// </summary>
        public static object ExecuteScalar(string query, params SqlParameter[] parameters)
        {
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(query, conn))
            {
                if (parameters != null && parameters.Length > 0)
                {
                    cmd.Parameters.AddRange(parameters);
                }
                return cmd.ExecuteScalar();
            }
        }

        /// <summary>
        /// Executes a SELECT query with parameters and fills the result into a DataTable.
        /// </summary>
        public static DataTable ExecuteDataTable(string query, params SqlParameter[] parameters)
        {
            var dataTable = new DataTable();
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(query, conn))
            {
                if (parameters != null && parameters.Length > 0)
                {
                    cmd.Parameters.AddRange(parameters);
                }

                using (var adapter = new SqlDataAdapter(cmd))
                {
                    adapter.Fill(dataTable);
                }
            }
            return dataTable;
        }

        /// <summary>Runs a stored procedure and preserves its affected-row result.</summary>
        public static int ExecuteProcedureNonQuery(string procedure, params SqlParameter[] parameters)
        {
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(procedure, conn) { CommandType = CommandType.StoredProcedure })
            {
                if (parameters != null && parameters.Length > 0)
                    cmd.Parameters.AddRange(parameters);
                return cmd.ExecuteNonQuery();
            }
        }

        /// <summary>Returns the first value selected by a stored procedure.</summary>
        public static object ExecuteProcedureScalar(string procedure, params SqlParameter[] parameters)
        {
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(procedure, conn) { CommandType = CommandType.StoredProcedure })
            {
                if (parameters != null && parameters.Length > 0)
                    cmd.Parameters.AddRange(parameters);
                return cmd.ExecuteScalar();
            }
        }

        /// <summary>Loads a stored procedure's result into the existing table mapper.</summary>
        public static DataTable ExecuteProcedureDataTable(string procedure, params SqlParameter[] parameters)
        {
            var dataTable = new DataTable();
            using (var conn = GetOpenConnection())
            using (var cmd = new SqlCommand(procedure, conn) { CommandType = CommandType.StoredProcedure })
            {
                if (parameters != null && parameters.Length > 0)
                    cmd.Parameters.AddRange(parameters);
                using (var adapter = new SqlDataAdapter(cmd))
                    adapter.Fill(dataTable);
            }
            return dataTable;
        }

        #endregion
    }
}
