//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.User
{
    public partial class EventPass
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Panel pnlSuccessBanner;
        protected global::System.Web.UI.WebControls.Literal litPassStatusPill;
        protected global::System.Web.UI.WebControls.Literal litPassEventTitle;

        protected global::System.Web.UI.WebControls.Literal litPassStudentName;
        protected global::System.Web.UI.WebControls.Literal litPassStudentId;
        protected global::System.Web.UI.WebControls.Literal litPassCourse;
        protected global::System.Web.UI.WebControls.Literal litPassYearSection;
        protected global::System.Web.UI.WebControls.Literal litPassEventDate;
        protected global::System.Web.UI.WebControls.Literal litPassEventTime;
        protected global::System.Web.UI.WebControls.Literal litPassVenue;

        protected global::System.Web.UI.WebControls.Literal litPassTicketRef;
        protected global::System.Web.UI.WebControls.Literal litPassSecurityToken;
    }
}
