//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.User
{
    public partial class EventRegistration
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        // Hidden field for step state
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentStep;

        // Navbar
        protected global::System.Web.UI.WebControls.Literal litNavAvatarInitials;
        protected global::System.Web.UI.WebControls.Literal litNavStudentName;
        protected global::System.Web.UI.WebControls.Literal litNavStudentId;

        // Context Banner / Header
        protected global::System.Web.UI.WebControls.Literal litContextEventTitle;
        protected global::System.Web.UI.WebControls.Literal litCapacityBadge;
        protected global::System.Web.UI.WebControls.Literal litContextEventDate;
        protected global::System.Web.UI.WebControls.Literal litContextVenue;
        protected global::System.Web.UI.WebControls.Literal litContextSchedule;

        // Error Panel
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorMsg;

        // Step 1: Event Information Controls
        protected global::System.Web.UI.WebControls.Literal litStep1Title;
        protected global::System.Web.UI.WebControls.Literal litStep1Description;
        protected global::System.Web.UI.WebControls.Literal litStep1Venue;
        protected global::System.Web.UI.WebControls.Literal litStep1Capacity;
        protected global::System.Web.UI.WebControls.Literal litStep1Date;
        protected global::System.Web.UI.WebControls.Literal litStep1Schedule;
        protected global::System.Web.UI.WebControls.Literal litStep1Audience;
        protected global::System.Web.UI.WebControls.Literal litStep1Spots;
        protected global::System.Web.UI.WebControls.Panel pnlEventPhoto;
        protected global::System.Web.UI.WebControls.Image imgEventPhoto;

        // Step 2: Student Profile Controls (View-Only)
        protected global::System.Web.UI.WebControls.Literal litProfileStudentId;
        protected global::System.Web.UI.WebControls.Literal litProfileFullName;
        protected global::System.Web.UI.WebControls.Literal litProfileEmail;
        protected global::System.Web.UI.WebControls.Literal litProfileCampus;
        protected global::System.Web.UI.WebControls.Literal litProfileDepartment;
        protected global::System.Web.UI.WebControls.Literal litProfileProgram;

        // Step 3: Academic Details Controls
        protected global::System.Web.UI.WebControls.DropDownList ddlYearLevel;
        protected global::System.Web.UI.WebControls.TextBox txtSection;
        protected global::System.Web.UI.WebControls.CheckBox chkTerms;
        protected global::System.Web.UI.WebControls.Button btnConfirmRegistration;
    }
}
