//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.User
{
    public partial class StudentProfilePage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm studentProfileForm;
        protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;
        protected global::System.Web.UI.WebControls.Literal litNavAvatar;
        protected global::System.Web.UI.WebControls.Literal litNavName;
        protected global::System.Web.UI.WebControls.Literal litNavId;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccessMsg;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorMsg;
        protected global::System.Web.UI.WebControls.Literal txtStudentId;
        protected global::System.Web.UI.WebControls.Literal txtCampusBranch;
        protected global::System.Web.UI.WebControls.Literal txtFirstName;
        protected global::System.Web.UI.WebControls.Literal txtMiddleName;
        protected global::System.Web.UI.WebControls.Literal txtLastName;
        protected global::System.Web.UI.WebControls.Literal txtDepartment;
        protected global::System.Web.UI.WebControls.Literal txtProgram;
        protected global::System.Web.UI.WebControls.Literal txtGender;
        protected global::System.Web.UI.WebControls.Literal txtYearLevel;
        protected global::System.Web.UI.WebControls.Literal txtEmail;
        protected global::System.Web.UI.WebControls.Literal txtRole;
        protected global::System.Web.UI.WebControls.Literal txtStatus;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnUpdatePassword;
    }
}
