//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class AccountManagement
    {
        protected global::System.Web.UI.WebControls.LinkButton btnExportAccountsCsv;
        protected global::System.Web.UI.WebControls.LinkButton btnOpenCreateAdminModal;
        protected global::System.Web.UI.WebControls.Panel pnlNotification;
        protected global::System.Web.UI.WebControls.Literal litNotificationMsg;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseNotification;
        protected global::System.Web.UI.WebControls.Literal litTotalAccounts;
        protected global::System.Web.UI.WebControls.Literal litActiveAdmins;
        protected global::System.Web.UI.WebControls.Literal litTotalStudents;
        protected global::System.Web.UI.WebControls.Literal litLockedAccounts;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlRoleFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.Button btnFilterApply;
        protected global::System.Web.UI.WebControls.Button btnResetFilter;
        protected global::System.Web.UI.WebControls.Literal litShowingCount;
        protected global::System.Web.UI.WebControls.Repeater rptUsers;
        protected global::System.Web.UI.WebControls.Panel pnlNoAccounts;
        protected global::System.Web.UI.WebControls.Button btnResetZeroState;
        protected global::System.Web.UI.WebControls.Panel pnlCreateAdminModal;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseCreateAdminModal;
        protected global::System.Web.UI.WebControls.TextBox txtNewAdminEmail;
        protected global::System.Web.UI.WebControls.TextBox txtNewAdminPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewAdminPasswordConfirm;
        protected global::System.Web.UI.WebControls.Button btnDismissCreateAdmin;
        protected global::System.Web.UI.WebControls.Button btnSaveNewAdmin;
        protected global::System.Web.UI.WebControls.Panel pnlManageModal;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseManageModal;
        protected global::System.Web.UI.WebControls.HiddenField hfManageUserId;
        protected global::System.Web.UI.WebControls.Image imgManageAvatar;
        protected global::System.Web.UI.WebControls.Panel pnlManageAvatarPlaceholder;
        protected global::System.Web.UI.WebControls.Literal litManageAvatarInitials;
        protected global::System.Web.UI.WebControls.Literal litManageDisplayName;
        protected global::System.Web.UI.WebControls.Literal litManageEmailSub;
        protected global::System.Web.UI.WebControls.Literal litManageUserIdText;
        protected global::System.Web.UI.WebControls.Literal litManageRoleBadge;
        protected global::System.Web.UI.WebControls.Literal litManageStatusBadge;
        protected global::System.Web.UI.WebControls.TextBox txtManageEmail;
        protected global::System.Web.UI.WebControls.DropDownList ddlManageRole;
        protected global::System.Web.UI.WebControls.DropDownList ddlManageStatus;
        protected global::System.Web.UI.WebControls.TextBox txtManageNewPassword;
        protected global::System.Web.UI.WebControls.Panel pnlManageStudentFields;
        protected global::System.Web.UI.WebControls.TextBox txtManageStudentId;
        protected global::System.Web.UI.WebControls.DropDownList ddlManageCampus;
        protected global::System.Web.UI.WebControls.TextBox txtManageFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtManageMiddleName;
        protected global::System.Web.UI.WebControls.TextBox txtManageLastName;
        protected global::System.Web.UI.WebControls.DropDownList ddlManageDepartment;
        protected global::System.Web.UI.WebControls.DropDownList ddlManageProgram;
        protected global::System.Web.UI.WebControls.DropDownList ddlManageGender;
        protected global::System.Web.UI.WebControls.FileUpload fuManagePhoto;
        protected global::System.Web.UI.WebControls.Button btnDismissManageModal;
        protected global::System.Web.UI.WebControls.Button btnSaveManageAccount;
        protected global::System.Web.UI.WebControls.Panel pnlLockModal;
        protected global::System.Web.UI.WebControls.Literal litLockModalTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseLockModal;
        protected global::System.Web.UI.WebControls.HiddenField hfLockTargetUserId;
        protected global::System.Web.UI.WebControls.Literal litLockActionVerb;
        protected global::System.Web.UI.WebControls.Literal litLockTargetEmail;
        protected global::System.Web.UI.WebControls.Button btnDismissLockModal;
        protected global::System.Web.UI.WebControls.Button btnConfirmToggleLock;
    }
}
