//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class Admin
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.HtmlControls.HtmlForm adminMasterForm;
        protected global::System.Web.UI.WebControls.Literal litAvatarInitials;
        protected global::System.Web.UI.WebControls.Literal litAdminEmail;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlPreviewBanner;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
