//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class AdminEvents
    {
        protected global::System.Web.UI.WebControls.Panel pnlFeedback;
        protected global::System.Web.UI.WebControls.Literal litFeedbackMessage;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseFeedback;

        protected global::System.Web.UI.WebControls.Literal litTotalMatrixCount;
        protected global::System.Web.UI.WebControls.Literal litOpenCount;
        protected global::System.Web.UI.WebControls.Literal litSoonCount;
        protected global::System.Web.UI.WebControls.Literal litCloseCount;

        protected global::System.Web.UI.WebControls.LinkButton btnTabAll;
        protected global::System.Web.UI.WebControls.Literal litBadgeAll;
        protected global::System.Web.UI.WebControls.LinkButton btnTabOpen;
        protected global::System.Web.UI.WebControls.Literal litBadgeOpen;
        protected global::System.Web.UI.WebControls.LinkButton btnTabSoon;
        protected global::System.Web.UI.WebControls.Literal litBadgeSoon;
        protected global::System.Web.UI.WebControls.LinkButton btnTabClose;
        protected global::System.Web.UI.WebControls.Literal litBadgeClose;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartmentFilter;

        protected global::System.Web.UI.WebControls.Repeater rptEventsMatrix;
        protected global::System.Web.UI.WebControls.Panel pnlNoEvents;
        protected global::System.Web.UI.WebControls.Button btnResetFilter;

        protected global::System.Web.UI.WebControls.Panel pnlCancelModal;
        protected global::System.Web.UI.WebControls.LinkButton btnDismissModal;
        protected global::System.Web.UI.WebControls.Literal litModalEventTitle;
        protected global::System.Web.UI.WebControls.HiddenField hCancelEventId;
        protected global::System.Web.UI.WebControls.HiddenField hfCancelEventId;
        protected global::System.Web.UI.WebControls.TextBox txtCancellationReason;
        protected global::System.Web.UI.WebControls.Button btnCancelDismiss;
        protected global::System.Web.UI.WebControls.Button btnConfirmCancellation;
    }
}
