//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class AttendanceScanner
    {
        protected global::System.Web.UI.WebControls.Literal litEventTitle;
        protected global::System.Web.UI.WebControls.Literal litEventDate;
        protected global::System.Web.UI.WebControls.Literal litEventVenue;
        protected global::System.Web.UI.WebControls.DropDownList ddlEvents;

        protected global::System.Web.UI.WebControls.Literal litCheckedInCount;
        protected global::System.Web.UI.WebControls.Literal litExpectedCount;
        protected global::System.Web.UI.WebControls.Literal litTurnoutRate;
        protected global::System.Web.UI.WebControls.Literal litCurrentAdminEmail;
    }
}
