//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class CreateEvent
    {
        /// <summary>
        /// hfActiveStep control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfActiveStep;

        /// <summary>
        /// btnPublishTop control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPublishTop;

        /// <summary>
        /// pnlSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        /// <summary>
        /// litSuccessMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSuccessMsg;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// litErrorMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litErrorMsg;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// txtVenueLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtVenueLocation;

        /// <summary>
        /// txtMaxCapacity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMaxCapacity;

        /// <summary>
        /// fuEventPhoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuEventPhoto;

        /// <summary>
        /// txtEventDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEventDate;

        /// <summary>
        /// txtEventStartTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEventStartTime;

        /// <summary>
        /// txtEventEndTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEventEndTime;

        /// <summary>
        /// txtRegStart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRegStart;

        /// <summary>
        /// txtRegEnd control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRegEnd;

        /// <summary>
        /// ddlBranch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlBranch;

        /// <summary>
        /// ddlDepartment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;

        /// <summary>
        /// hfSelectedPrograms control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedPrograms;

        /// <summary>
        /// ddlYearLevel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYearLevel;

        /// <summary>
        /// txtNewSponsor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewSponsor;

        /// <summary>
        /// btnAddSponsor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddSponsor;

        /// <summary>
        /// rptSponsors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSponsors;

        /// <summary>
        /// litNoSponsorsHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNoSponsorsHint;

        /// <summary>
        /// btnPreset1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnPreset1;

        /// <summary>
        /// btnPreset2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnPreset2;

        /// <summary>
        /// btnPreset3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnPreset3;

        /// <summary>
        /// btnPreset4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnPreset4;

        /// <summary>
        /// btnPreset5 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnPreset5;



        /// <summary>
        /// btnConfirmPublish control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmPublish;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new _241611JalopEventsManagement.Frontend.Admin.Admin Master
        {
            get
            {
                return ((_241611JalopEventsManagement.Frontend.Admin.Admin)(base.Master));
            }
        }
    }
}
