//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litTotalEvents;
        protected global::System.Web.UI.WebControls.Literal litUpcomingCount;
        protected global::System.Web.UI.WebControls.Literal litTotalRegistrations;
        protected global::System.Web.UI.WebControls.Literal litFillRate;
        protected global::System.Web.UI.WebControls.Literal litStudentCount;
        protected global::System.Web.UI.WebControls.Repeater rptEvents;
        protected global::System.Web.UI.WebControls.Panel pnlNoEvents;
    }
}
