//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class EventAnalytics
    {
        protected global::System.Web.UI.WebControls.Literal litEventTitle;
        protected global::System.Web.UI.WebControls.Literal litEventDate;
        protected global::System.Web.UI.WebControls.Literal litEventVenue;
        protected global::System.Web.UI.WebControls.Literal litEventCapacitySummary;
        protected global::System.Web.UI.WebControls.Literal litEventStatusBadge;
        protected global::System.Web.UI.WebControls.DropDownList ddlEvents;

        protected global::System.Web.UI.WebControls.LinkButton btnExportSummaryPdf;
        protected global::System.Web.UI.WebControls.LinkButton btnExportComprehensiveCsv;

        // Tab 1: Before - Pre-Event Analytics
        protected global::System.Web.UI.WebControls.Literal litBeforePreRegistered;
        protected global::System.Web.UI.WebControls.Literal litBeforeTotalReserved;
        protected global::System.Web.UI.WebControls.Literal litBeforeCancelled;
        protected global::System.Web.UI.WebControls.Literal litBeforeAttritionRate;
        protected global::System.Web.UI.WebControls.Literal litBeforeSaturationRate;
        protected global::System.Web.UI.WebControls.Literal litBeforeSaturationStatus;
        protected global::System.Web.UI.WebControls.Literal litBeforeAvailableQuota;
        protected global::System.Web.UI.WebControls.Literal litBeforeDaysUntilLaunch;
        protected global::System.Web.UI.WebControls.Literal litSaturationPercentDisplay;
        protected global::System.Web.UI.WebControls.Literal litCapacityMaxDisplay;
        protected global::System.Web.UI.WebControls.Literal litSaturationProgressBar;
        protected global::System.Web.UI.WebControls.Literal litDemographicsJson;
        protected global::System.Web.UI.WebControls.Repeater rptBranchDistribution;
        protected global::System.Web.UI.WebControls.Repeater rptDepartmentDistribution;
        protected global::System.Web.UI.WebControls.Repeater rptCourseDistribution;
        protected global::System.Web.UI.WebControls.Repeater rptYearDistribution;
        protected global::System.Web.UI.WebControls.Repeater rptRegistrationVelocity;

        // Tab 2: During - Live Gate Telemetry
        protected global::System.Web.UI.WebControls.Literal litDuringCheckedIn;
        protected global::System.Web.UI.WebControls.Literal litDuringRosterTotal;
        protected global::System.Web.UI.WebControls.Literal litDuringTurnoutRate;
        protected global::System.Web.UI.WebControls.Literal litDuringVenueOccupancy;
        protected global::System.Web.UI.WebControls.Literal litDuringUnscannedCohort;
        protected global::System.Web.UI.WebControls.Literal litDuringPeakWindow;
        protected global::System.Web.UI.WebControls.Repeater rptCheckInIntervals;

        // Tab 3: After - Post-Event Performance Audit
        protected global::System.Web.UI.WebControls.Literal litAfterPreRegisteredTotal;
        protected global::System.Web.UI.WebControls.Literal litAfterActualAttended;
        protected global::System.Web.UI.WebControls.Literal litAfterNoShows;
        protected global::System.Web.UI.WebControls.Literal litAfterCancellations;
        protected global::System.Web.UI.WebControls.Literal litAfterRetentionRate;
        protected global::System.Web.UI.WebControls.Literal litAfterTopDepartment;
        protected global::System.Web.UI.WebControls.Repeater rptDemographicAudit;
    }
}
