//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class EventPreRegistered
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlertBox;
        protected global::System.Web.UI.WebControls.Label lblAlertMessage;

        protected global::System.Web.UI.WebControls.Literal litEventTitle;
        protected global::System.Web.UI.WebControls.Literal litEventDate;
        protected global::System.Web.UI.WebControls.Literal litEventVenue;
        protected global::System.Web.UI.WebControls.Literal litEventCapacitySummary;
        protected global::System.Web.UI.WebControls.Literal litEventStatusBadge;
        protected global::System.Web.UI.WebControls.DropDownList ddlEvents;

        protected global::System.Web.UI.WebControls.Literal litKpiPreRegistered;
        protected global::System.Web.UI.WebControls.Literal litKpiAvailablePool;
        protected global::System.Web.UI.WebControls.Literal litKpiCancelled;
        protected global::System.Web.UI.WebControls.Literal litKpiOccupancyRate;

        protected global::System.Web.UI.WebControls.DropDownList ddlFilterDepartment;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterCourse;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterYearLevel;

        protected global::System.Web.UI.WebControls.LinkButton btnExportCsv;

        protected global::System.Web.UI.WebControls.Literal litTabCountPreReg;
        protected global::System.Web.UI.WebControls.Literal litTabCountCancelled;

        protected global::System.Web.UI.WebControls.Repeater rptPreRegistered;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyPreRegistered;

        protected global::System.Web.UI.WebControls.Repeater rptCancelled;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCancelled;
    }
}
