//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class EventAttendance
    {
        protected global::System.Web.UI.WebControls.Literal litEventTitle;
        protected global::System.Web.UI.WebControls.Literal litEventDate;
        protected global::System.Web.UI.WebControls.Literal litEventVenue;
        protected global::System.Web.UI.WebControls.Literal litCheckedInCount;
        protected global::System.Web.UI.WebControls.Literal litCapacitySummary;
        protected global::System.Web.UI.WebControls.DropDownList ddlEvents;

        protected global::System.Web.UI.WebControls.Literal litKpiTotalCheckedIn;
        protected global::System.Web.UI.WebControls.Literal litKpiTurnoutRate;
        protected global::System.Web.UI.WebControls.Literal litKpiLatestCheckIn;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartmentFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlProgramFilter;

        protected global::System.Web.UI.WebControls.Repeater rptCheckedInAttendees;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyRoster;
    }
}
