//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class EventDetails
    {
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccessMsg;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseSuccess;

        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorMsg;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseError;

        protected global::System.Web.UI.WebControls.Panel pnlDemoNotice;
        protected global::System.Web.UI.WebControls.Literal litDemoNotice;

        protected global::System.Web.UI.WebControls.Literal litHeaderEventId;
        protected global::System.Web.UI.WebControls.Literal litHeaderTitle;
        protected global::System.Web.UI.WebControls.Literal litHeaderStatus;
        protected global::System.Web.UI.WebControls.Literal litEventDate;
        protected global::System.Web.UI.WebControls.Literal litEventVenue;
        protected global::System.Web.UI.WebControls.Literal litEventCapacitySummary;
        protected global::System.Web.UI.WebControls.DropDownList ddlEvents;
        protected global::System.Web.UI.WebControls.PlaceHolder phHeaderHidden;

        protected global::System.Web.UI.WebControls.Literal litModeDescription;
        protected global::System.Web.UI.WebControls.PlaceHolder phViewActions;
        protected global::System.Web.UI.WebControls.Button btnToggleArchive;
        protected global::System.Web.UI.WebControls.Button btnToggleEdit;
        protected global::System.Web.UI.WebControls.PlaceHolder phEditActions;
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;
        protected global::System.Web.UI.WebControls.Button btnSaveChanges;
        protected global::System.Web.UI.WebControls.Panel pnlArchivedNotice;

        protected global::System.Web.UI.WebControls.PlaceHolder phGeneralView;
        protected global::System.Web.UI.WebControls.Literal litTitleView;
        protected global::System.Web.UI.WebControls.Literal litVenueView;
        protected global::System.Web.UI.WebControls.Literal litCapacityView;
        protected global::System.Web.UI.WebControls.Literal litDescView;

        protected global::System.Web.UI.WebControls.PlaceHolder phGeneralEdit;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtVenueLocation;
        protected global::System.Web.UI.WebControls.TextBox txtMaxCapacity;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        protected global::System.Web.UI.WebControls.PlaceHolder phScheduleView;
        protected global::System.Web.UI.WebControls.Literal litEventDateView;
        protected global::System.Web.UI.WebControls.Literal litEventHoursView;
        protected global::System.Web.UI.WebControls.Literal litRegStartView;
        protected global::System.Web.UI.WebControls.Literal litRegEndView;

        protected global::System.Web.UI.WebControls.PlaceHolder phScheduleEdit;
        protected global::System.Web.UI.WebControls.TextBox txtEventDate;
        protected global::System.Web.UI.WebControls.TextBox txtStartTime;
        protected global::System.Web.UI.WebControls.TextBox txtEndTime;
        protected global::System.Web.UI.WebControls.TextBox txtRegStart;
        protected global::System.Web.UI.WebControls.TextBox txtRegEnd;

        protected global::System.Web.UI.WebControls.Image imgWideBanner;
        protected global::System.Web.UI.WebControls.PlaceHolder phWideUpload;
        protected global::System.Web.UI.WebControls.HiddenField hfEditPhotoBase64;
        protected global::System.Web.UI.WebControls.HiddenField hfEditPhotoFileName;
        protected global::System.Web.UI.WebControls.FileUpload fuWideBanner;

        protected global::System.Web.UI.WebControls.Image imgSquareBanner;
        protected global::System.Web.UI.WebControls.PlaceHolder phSquareUpload;
        protected global::System.Web.UI.WebControls.FileUpload fuSquareBanner;

        protected global::System.Web.UI.WebControls.PlaceHolder phDemographicsView;
        protected global::System.Web.UI.WebControls.Literal litBranchView;
        protected global::System.Web.UI.WebControls.Literal litDeptView;
        protected global::System.Web.UI.WebControls.Literal litYearLevelView;
        protected global::System.Web.UI.WebControls.Literal litProgramsChips;

        protected global::System.Web.UI.WebControls.PlaceHolder phDemographicsEdit;
        protected global::System.Web.UI.WebControls.DropDownList ddlBranch;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.WebControls.DropDownList ddlYearLevel;
        protected global::System.Web.UI.WebControls.TextBox txtPrograms;

        protected global::System.Web.UI.WebControls.Repeater rptSponsors;
        protected global::System.Web.UI.WebControls.Literal litNoSponsors;
        protected global::System.Web.UI.WebControls.PlaceHolder phAddSponsor;
        protected global::System.Web.UI.WebControls.TextBox txtNewSponsor;
        protected global::System.Web.UI.WebControls.Button btnAddSponsor;

        protected global::System.Web.UI.WebControls.Literal litSidebarStatus;
        protected global::System.Web.UI.WebControls.Literal litOccupancyPct;
        protected global::System.Web.UI.WebControls.Literal litOccupancyCount;
        protected global::System.Web.UI.WebControls.Literal litRemainingSpots;

        protected global::System.Web.UI.WebControls.Literal litMetaEventId;
        protected global::System.Web.UI.WebControls.Literal litMetaSponsorCount;

        public new _241611JalopEventsManagement.Frontend.Admin.Admin Master
        {
            get => ((_241611JalopEventsManagement.Frontend.Admin.Admin)(base.Master));
        }
    }
}
