//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class EventHistory
    {
        protected global::System.Web.UI.WebControls.LinkButton btnExportArchiveCsv;
        protected global::System.Web.UI.WebControls.Panel pnlNotification;
        protected global::System.Web.UI.WebControls.Literal litNotificationMsg;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseNotification;
        protected global::System.Web.UI.WebControls.Literal litTotalArchived;
        protected global::System.Web.UI.WebControls.Literal litTotalCompleted;
        protected global::System.Web.UI.WebControls.Literal litTotalCancelled;
        protected global::System.Web.UI.WebControls.Literal litTurnoutAvg;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlAcademicYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlSemester;
        protected global::System.Web.UI.WebControls.DropDownList ddlOutcomeStatus;
        protected global::System.Web.UI.WebControls.Button btnFilterApply;
        protected global::System.Web.UI.WebControls.Button btnResetFilter;
        protected global::System.Web.UI.WebControls.Literal litShowingCount;
        protected global::System.Web.UI.WebControls.Repeater rptEventHistory;
        protected global::System.Web.UI.WebControls.Panel pnlNoRecords;
        protected global::System.Web.UI.WebControls.Button btnResetZeroState;
        protected global::System.Web.UI.WebControls.Panel pnlReportModal;
        protected global::System.Web.UI.WebControls.Literal litModalEventCode;
        protected global::System.Web.UI.WebControls.Literal litModalEventTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseModal;
        protected global::System.Web.UI.WebControls.Literal litModalStatusPill;
        protected global::System.Web.UI.WebControls.Literal litModalAcademicTerm;
        protected global::System.Web.UI.WebControls.Literal litModalVenue;
        protected global::System.Web.UI.WebControls.Literal litModalDateTime;
        protected global::System.Web.UI.WebControls.Literal litModalDepartment;
        protected global::System.Web.UI.WebControls.Literal litModalProgram;
        protected global::System.Web.UI.WebControls.Panel pnlModalCancellationReason;
        protected global::System.Web.UI.WebControls.Literal litModalCancellationReason;
        protected global::System.Web.UI.WebControls.Literal litModalCapacity;
        protected global::System.Web.UI.WebControls.Literal litModalPreReg;
        protected global::System.Web.UI.WebControls.Literal litModalAttended;
        protected global::System.Web.UI.WebControls.Literal litModalTurnoutPct;
        protected global::System.Web.UI.WebControls.HiddenField hfModalEventId;
        protected global::System.Web.UI.WebControls.Button btnExportSingleReportCsv;
        protected global::System.Web.UI.WebControls.Button btnDismissModal;
    }
}
