//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class StudentList
    {
        protected global::System.Web.UI.WebControls.LinkButton btnExportCsv;
        protected global::System.Web.UI.WebControls.LinkButton btnOpenBatchModal;
        protected global::System.Web.UI.WebControls.LinkButton btnOpenAddModal;
        protected global::System.Web.UI.WebControls.Panel pnlNotification;
        protected global::System.Web.UI.WebControls.Literal litNotificationMsg;
        protected global::System.Web.UI.WebControls.Literal litTotalStudents;
        protected global::System.Web.UI.WebControls.Literal litActiveAccounts;
        protected global::System.Web.UI.WebControls.Literal litSuspendedAccounts;
        protected global::System.Web.UI.WebControls.Literal litDistinctPrograms;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnClearFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartmentFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlProgramFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.Literal litShowingCount;
        protected global::System.Web.UI.WebControls.Repeater rptStudents;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyState;
        protected global::System.Web.UI.WebControls.Button btnEmptyClear;
        protected global::System.Web.UI.WebControls.Panel pnlAddModal;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseAddModal;
        protected global::System.Web.UI.WebControls.TextBox txtAddStudentId;
        protected global::System.Web.UI.WebControls.TextBox txtAddEmail;
        protected global::System.Web.UI.WebControls.TextBox txtAddFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtAddMiddleName;
        protected global::System.Web.UI.WebControls.TextBox txtAddLastName;
        protected global::System.Web.UI.WebControls.TextBox txtAddBirthDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddGender;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddCampus;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddDepartment;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddProgram;
        protected global::System.Web.UI.WebControls.Button btnCancelAdd;
        protected global::System.Web.UI.WebControls.Button btnSaveNewStudent;
        protected global::System.Web.UI.WebControls.Panel pnlEditModal;
        protected global::System.Web.UI.WebControls.Literal litEditStudentIdHeading;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseEditModal;
        protected global::System.Web.UI.WebControls.HiddenField hfEditStudentId;
        protected global::System.Web.UI.WebControls.TextBox txtEditStudentId;
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEditFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtEditMiddleName;
        protected global::System.Web.UI.WebControls.TextBox txtEditLastName;
        protected global::System.Web.UI.WebControls.TextBox txtEditBirthDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditGender;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditCampus;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditDepartment;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditProgram;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditStatus;
        protected global::System.Web.UI.WebControls.Literal litEditStructuredPassword;
        protected global::System.Web.UI.WebControls.TextBox txtEditNewPassword;
        protected global::System.Web.UI.WebControls.HiddenField hfActiveEditTab;
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;
        protected global::System.Web.UI.WebControls.Button btnUpdateStudent;
        protected global::System.Web.UI.WebControls.Panel pnlResetModal;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseResetModal;
        protected global::System.Web.UI.WebControls.HiddenField hfResetStudentId;
        protected global::System.Web.UI.WebControls.Literal litResetStudentInfo;
        protected global::System.Web.UI.WebControls.Literal litDefaultTempPassword;
        protected global::System.Web.UI.WebControls.TextBox txtCustomPassword;
        protected global::System.Web.UI.WebControls.Button btnCancelReset;
        protected global::System.Web.UI.WebControls.Button btnConfirmReset;
        protected global::System.Web.UI.WebControls.Panel pnlBatchModal;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseBatchModal;
        protected global::System.Web.UI.WebControls.FileUpload fuCsvRoster;
        protected global::System.Web.UI.WebControls.LinkButton btnDownloadTemplate;
        protected global::System.Web.UI.WebControls.Button btnProcessCsv;
    }
}
