//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopEventsManagement.Frontend.Admin
{
    public partial class TestConnection
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// btnRetest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRetest;

        /// <summary>
        /// phStatusBadge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phStatusBadge;

        /// <summary>
        /// lblLatency control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLatency;

        /// <summary>
        /// lblTimestamp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTimestamp;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// lblErrorMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorMessage;

        /// <summary>
        /// lblConnectionString control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblConnectionString;
    }
}
